const keyList = [
    //1 row
    {rutext:'ё',text: '`', key : 'graveaccent',style : {gridColumnStart: 'span 1'}},
    {text: '1', key : '1',style : {gridColumnStart: 'span 1'}},
    {text: '2', key : '2',style : {gridColumnStart: 'span 1'}},
    {text: '3', key : '3',style : {gridColumnStart: 'span 1'}},
    {text: '4', key : '4',style : {gridColumnStart: 'span 1'}},
    {text: '5', key : '5',style : {gridColumnStart: 'span 1'}},
    {text: '6', key : '6',style : {gridColumnStart: 'span 1'}},
    {text: '7', key : '7',style : {gridColumnStart: 'span 1'}},
    {text: '8', key : '8',style : {gridColumnStart: 'span 1'}},
    {text: '9', key : '9',style : {gridColumnStart: 'span 1'}},
    {text: '0', key : '0',style : {gridColumnStart: 'span 1'}},
    {text: '-', key : 'dash',style : {gridColumnStart: 'span 1'}},
    {text: '=', key : 'equalsign',style : {gridColumnStart: 'span 1'}},
    {text: 'backspace', key : 'backspace',style : {fontSize:'1em',gridColumnStart: 'span 2'}, func: 'back' },
    //2 row
    {text: 'tab', key : 'tab',style : {fontSize:'1em',gridColumnStart: 'span 1'},func:'tab'},
    {rutext:'й',text: 'q', key : 'q',style : {gridColumnStart: 'span 1'}},
    {rutext:'ц',text: 'w', key : 'w',style : {gridColumnStart: 'span 1'}},
    {rutext:'у',text: 'e', key : 'e',style : {gridColumnStart: 'span 1'}},
    {rutext:'к',text: 'r', key : 'r',style : {gridColumnStart: 'span 1'}},
    {rutext:'е',text: 't', key : 't',style : {gridColumnStart: 'span 1'}},
    {rutext:'н',text: 'y', key : 'y',style : {gridColumnStart: 'span 1'}},
    {rutext:'г',text: 'u', key : 'u',style : {gridColumnStart: 'span 1'}},
    {rutext:'ш',text: 'i', key : 'i',style : {gridColumnStart: 'span 1'}},
    {rutext:'щ',text: 'o', key : 'o',style : {gridColumnStart: 'span 1'}},
    {rutext:'з',text: 'p', key : 'p',style : {gridColumnStart: 'span 1'}},
    {rutext:'х',text: '[', key : 'openbracket',style : {gridColumnStart: 'span 1'}},
    {rutext:'ъ',text: ']', key : 'closebracket',style : {gridColumnStart: 'span 1'}},
    {text: '\\', key : 'backslash',style : {gridColumnStart: 'span 1'}},
    {text: 'del', key : 'delete',style : {fontSize:'1.3em',gridColumnStart: 'span 1'}, func: 'delet'},
    //3 row
    {text: 'capslock', key : 'capslock',style : {fontSize:'1.3em',gridColumnStart: 'span 2'},func:'capslock'},
    {rutext:'ф',text: 'a', key : 'a',style : {gridColumnStart: 'span 1'}},
    {rutext:'ы',text: 's', key : 's',style : {gridColumnStart: 'span 1'}},
    {rutext:'в',text: 'd', key : 'd',style : {gridColumnStart: 'span 1'}},
    {rutext:'а',text: 'f', key : 'f',style : {gridColumnStart: 'span 1'}},
    {rutext:'п',text: 'g', key : 'g',style : {gridColumnStart: 'span 1'}},
    {rutext:'р',text: 'h', key : 'h',style : {gridColumnStart: 'span 1'}},
    {rutext:'о',text: 'j', key : 'j',style : {gridColumnStart: 'span 1'}},
    {rutext:'л',text: 'k', key : 'k',style : {gridColumnStart: 'span 1'}},
    {rutext:'д',text: 'l', key : 'l',style : {gridColumnStart: 'span 1'}},
    {rutext:'э',text: ';', key : 'semicolon',style : {gridColumnStart: 'span 1'}},
    {text: '\'', key : 'singlequote',style : {gridColumnStart: 'span 1'}},
    {text: 'enter', key : 'enter',style : {fontSize:'1.3em',gridColumnStart: 'span 2'},func:'enter'},
    //4 row
    {text: 'shift', key : 'shift',style : {fontSize:'1em',gridColumnStart: 'span 2'},func:'shift'},
    {rutext:'я',text: 'z', key : 'z',style : {gridColumnStart: 'span 1'}},
    {rutext:'ч',text: 'x', key : 'x',style : {gridColumnStart: 'span 1'}},
    {rutext:'с',text: 'c', key : 'c',style : {gridColumnStart: 'span 1'}},
    {rutext:'м',text: 'v', key : 'v',style : {gridColumnStart: 'span 1'}},
    {rutext:'и',text: 'b', key : 'b',style : {gridColumnStart: 'span 1'}},
    {rutext:'т',text: 'n', key : 'n',style : {gridColumnStart: 'span 1'}},
    {rutext:'ь',text: 'm', key : 'm',style : {gridColumnStart: 'span 1'}},
    {rutext:'б',text: ',', key : 'comma',style : {gridColumnStart: 'span 1'}},
    {rutext:'ю',text: '.', key : 'period',style : {gridColumnStart: 'span 1'}},
    {text: '/', key : 'forwardslash',style : {gridColumnStart: 'span 1'}},
    {text: '▲', key : 'uparrow',style : {gridColumnStart: 'span 3'},func:'up'},
    //5 row
    {text: 'ctrl', key : 'ctrl',style : {fontSize:'1em',gridColumnStart: 'span 1'},func:'ctrl'},
    {text: 'op', key : 'leftwindowkey',style : {fontSize:'1.3em',gridColumnStart: 'span 1'},func:'win'},
    {text: 'alt', key : 'alt',style : {fontSize:'1.3em',gridColumnStart: 'span 1'},func:'alt'},
    {text: ' ', key : 'space',style : {gridColumnStart: 'span 9'}},
    {text: '◄', key : 'leftarrow',style : {gridColumnStart: 'span 1'},func:'left'},
    {text: '▼', key : 'downarrow',style : {gridColumnStart: 'span 1'},func:'down'},
    {text: '►', key : 'rightarrow',style : {gridColumnStart: 'span 1'},func:'right'},

]

export default keyList